version: "3.8"
services:
    db:
        image: postgres:9.4-alpine 
        container_name: wager_postgres
        volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
        - 5432:5432
        environment:
        - POSTGRES_DB=wager
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres 

    wager:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: wager_api
        ports:
        - 8080:8080
        depends_on:
        - db
        restart: always
        environment:
        - DATABASE__HOST=db
        - DATABASE__PASSWORD=postgres
        - DATABASE__PORT=5432
      


